<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Creator
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website.
baseurl: "/personal" # the subpath of your site, e.g. /blog
url: "https://qaz-creator.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# only get the first sentence for the excerpt
excerpt_separator:  .
# NOt default
author: Creator

copyright:             © <!--copyyears--> Creator; All rights reserved.

title-logo: /images/icon.png
# Build settings
markdown: kramdown
# Remove minima theme as it is now a regular theme
# theme: minima
plugins:
  - jekyll-feed
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
github: [metadata]

social:
  - title: email
    url: mailto:creator@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/
  - title: linkedin
    url: https://www.linkedin.com/in/

